### ISSUE TITLE
Add ability for filters to be added by apps that include the hex

### ISSUE THREAD

**Issue by nulian** [bettyblocks/liquid-elixir#14]
Make it so filters can be added on including liquid elixir. 
So custom filters can be used.

**Comment by Wijnand** [comment]
Yes, filters, tags etc should all be something you as package user can add in 2 ways:
- Compiled in
- Dynamic via the GenServer construction we have in place now. I think usage of the dynamic extensions should be optional and off by default, so no GenServer calls should be needed for parsing and rendering templates. If dynamic extensions are enabled liquid should start the required GenServers and perform lookups as a fallback when a tag or filter is not found.

**Comment by Wijnand** [comment]
We are thinking something along the lines of:
config :liquid,
  extra_filters_module: [MyApp.Liquid.Filters],
  enable_dynamic_filters: false,
  extra_tags:%{myawesometag: { MyApp.Liquid.Tags,  Liquid.Tag }},
  enable_dynamic_tags: true


We also have the custom filesystems but we are not yet sure how to handle those.
