### ISSUE TITLE
Reduce user based atom usage in liquid package

### ISSUE THREAD

**Issue by nulian** [bettyblocks/liquid-elixir#2]
Only allow atom conversion on stuff with whitelists because of atom limit.

**Comment by nulian** [comment]
Fixed assigns atom usage by converting to string keys. Still needs a pass to check if all user input is not using the correct string keys.

**Comment by art4ride** [comment]
So am I right that we want to force user to use strings as a keys in his own structs too?
Like:
``` elixir
defmodule User do              
  defstruct "name with space": "one"
end      
```
