### ISSUE TITLE
Passing maps with functions

### ISSUE THREAD

**Issue by nsweeting** [bettyblocks/liquid-elixir#39]
Hi there,

I'm wondering if it would be possible to have "lazy" data access when rendering templates. This could be achieved by passing a map that contains functions. When rendering, it would simply call the function and output its return value. This could provide much improved performance in certain situations.

Cheers

**Comment by nulian** [comment]
We currently have this with structs and using protocols.
With defining the Liquid.Matcher you can call whatever you want on the struct. And not all data needs to be in the struct just a reference to the true data you want to handle.
