### ISSUE TITLE
Use of String.to_atom in Liquid.Registers

### ISSUE THREAD

**Issue by nsweeting** [bettyblocks/liquid-elixir#49]
Hi there,

As of now, `Liquid.Registers` does a `String.to_atom` on binary lookups. Since atoms are not garbage collected, this introduces a security flaw where an infinite amount of atoms can be generated from bad tags.

https://github.com/bettyblocks/liquid-elixir/blob/e03a5a0cd21078d432937ef5561a93533d2ffaf8/lib/liquid/registers.ex#L31

This should be replaced with `String.to_existing_atom`.

Cheers

**Comment by nulian** [comment]
Fixed in 0.9.1
