### ISSUE TITLE
Implement all the default liquid filters

### ISSUE THREAD

**Issue by nulian** [bettyblocks/liquid-elixir#6]
Implement all the standard liquid filters from liquid 3.0

- [x]  append  - append a string e.g.  {{ 'foo' | append:'bar' }} #=> 'foobar'  
- [x] capitalize  - capitalize words in the input sentence
- [x] ceil  - rounds a number up to the nearest integer, e.g.  {{ 4.6 | ceil }} #=> 5  
- [x] date  - reformat a date (syntax reference)
- [x]  default  - returns the given variable unless it is null or the empty string, when it will return the given value, e.g.  {{ undefined_variable | default: "Default value" }} #=> "Default value"  
- [x]  divided_by  - integer division e.g.  {{ 10 | divided_by:3 }} #=> 3  
- [x]  downcase  - convert an input string to lowercase
- [x]  escape_once  - returns an escaped version of html without affecting existing escaped entities
- [x]  escape  - html escape a string
- [x]  first  - get the first element of the passed in array
- [x]  floor  - rounds a number down to the nearest integer, e.g.  {{ 4.6 | floor }} #=> 4  
- [x]  join  - join elements of the array with certain character between them
- [x]  last  - get the last element of the passed in array
- [x]  lstrip  - strips all whitespace from the beginning of a string
- [x]  map  - map/collect an array on a given property
- [x]  minus  - subtraction e.g.  {{ 4 | minus:2 }} #=> 2  
- [x]  modulo  - remainder, e.g.  {{ 3 | modulo:2 }} #=> 1  
- [x]  newline_to_br  - replace each newline (\n) with html break
- [ ]  pluralize  - return the second word if the input is not  1 , otherwise return the first word e.g.  {{ 3 | pluralize: 'item', 'items' }} #=> 'items'  
- [x]  plus  - addition e.g.  {{ '1' | plus:'1' }} #=> 2 ,  {{ 1 | plus:1 }} #=> 2  
- [x]  prepend  - prepend a string e.g.  {{ 'bar' | prepend:'foo' }} #=> 'foobar'  
- [x]  remove_first  - remove the first occurrence e.g.  {{ 'barbar' | remove_first:'bar' }} #=> 'bar'  
- [x]  remove  - remove each occurrence e.g.  {{ 'foobarfoobar' | remove:'foo' }} #=> 'barbar'  
- [x] replace_first  - replace the first occurrence e.g.  {{ 'barbar' | replace_first:'bar','foo' }} #=> 'foobar'  
- [x]  replace  - replace each occurrence e.g.  {{ 'foofoo' | replace:'foo','bar' }} #=> 'barbar'  
- [x]  reverse  - reverses the passed in array
- [x]  round  - rounds input to the nearest integer or specified number of decimals e.g.  {{ 4.5612 | round: 2 }} #=> 4.56  
- [x]  rstrip  - strips all whitespace from the end of a string
- [x]  size  - return the size of an array or string
- [x]  slice  - slice a string. Takes an offset and length, e.g.  {{ "hello" | slice: -3, 3 }} #=> llo  
- [x]  sort  - sort elements of the array
- [x]  split  - split a string on a matching pattern e.g.  {{ "a~b" | split:"~" }} #=> ['a','b']  
- [x]  strip_html  - strip html from string
- [x]  strip_newlines  - strip all newlines (\n) from string
- [x]  strip  - strips all whitespace from both ends of the string
- [x]  times  - multiplication e.g  {{ 5 | times:4 }} #=> 20  
- [x]  truncate  - truncate a string down to x characters. It also accepts a second parameter that will append to the string e.g.  {{ 'foobarfoobar' | truncate: 5, '.' }} #=> 'foob.'  
- [x]  truncatewords  - truncate a string down to x words
- [x]  uniq  - removed duplicate elements from an array, optionally using a given property to test for uniqueness
- [x]  upcase  - convert an input string to uppercase
- [x]  url_encode  - url encode a string

**Comment by art4ride** [comment]
Hi @nulian ,

I've got a question about capitalise function. 

In the case of an input "hello world!" should it the output be like
"Hello world!" or  "Hello World!"?

**Comment by nulian** [comment]
The original liquid documentation isn't really clear about it and there tests either I'll give it a try in my ruby client. Which you can always do to double check the results using the ruby liquid version and testing it in it.

**Comment by nulian** [comment]
https://github.com/Shopify/liquid Shouldn't be too hard to load in a ruby console.

And capitalize should be "Hello world!" after trying it in liquid ruby version

**Comment by Wijnand** [comment]
@art4ride are all these filters implemented now?

**Comment by nulian** [comment]
Updated the list with what is implemented

**Comment by besniksh95** [comment]
Hi @nulian,

I am trying to use the filter slice, but it doesn't work.
Example: {{ "hello" | slice: -3, 3 }}
I tested it in version 0.8 and 0.9.

**Comment by khedaywi** [comment]
> Hi @nulian,
> 
> I am trying to use the filter slice, but it doesn't work.
> Example: {{ "hello" | slice: -3, 3 }}
> I tested it in version 0.8 and 0.9.

This has been resolved with the pull request #95 once it gets merged to master.
